CREATE ROLE guest NOLOGIN;
CREATE ROLE candidate NOLOGIN;
CREATE ROLE vgk_rescuer NOLOGIN;
CREATE ROLE operator NOLOGIN;
CREATE ROLE admin WITH LOGIN PASSWORD 'admin';

CREATE USER app WITH PASSWORD 'app';
